import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Use | Lanka News Room',
  description: 'Terms of Use for Lanka News Room - Understand the terms and conditions for using our AI-powered news platform.',
};

export default function TermsOfUsePage() {
  const currentDate = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });

  return (
    <div className="min-h-screen bg-[#F5F5F5]">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="bg-white rounded-xl shadow-sm border border-[#E8EAED] p-8">
          <h1 className="text-3xl font-bold text-[#202124] mb-2">Terms of Use</h1>
          
          <p className="text-[#5F6368] mb-8">
            <strong>Last updated:</strong> {currentDate}
          </p>

          <div className="prose prose-gray max-w-none">
            <section className="mb-8">
              <p className="text-[#5F6368] mb-6 leading-relaxed">
                By accessing or using Lanka News Room, you agree to these Terms of Use.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-[#202124] mb-4">1. Nature of the Platform</h2>
              <p className="text-[#5F6368] mb-4 leading-relaxed">
                Lanka News Room is an AI-powered news room platform.
              </p>
              <ul className="list-disc pl-6 text-[#5F6368] mb-4 space-y-2">
                <li>We do not write original news articles</li>
                <li>All summaries are generated by our artificial intelligence system</li>
                <li>Content is created by analyzing information from multiple public sources</li>
                <li>AI-generated content may contain errors or omissions</li>
              </ul>
              <p className="text-[#5F6368] mb-4 leading-relaxed">
                Always verify important information using original sources.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-[#202124] mb-4">2. Neutrality</h2>
              <p className="text-[#5F6368] mb-4 leading-relaxed">
                Lanka News Room is a neutral platform.
              </p>
              <p className="text-[#5F6368] mb-4 leading-relaxed">
                We do not support or oppose:
              </p>
              <ul className="list-disc pl-6 text-[#5F6368] mb-4 space-y-2">
                <li>Any political party or ideology</li>
                <li>Any religion</li>
                <li>Any ethnic or racial group</li>
              </ul>
              <p className="text-[#5F6368] mb-4 leading-relaxed">
                Our goal is to provide factual, multi-source summaries only.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-[#202124] mb-4">3. Copyright & Ownership</h2>
              <ul className="list-disc pl-6 text-[#5F6368] mb-4 space-y-2">
                <li>We do not claim ownership of original news articles</li>
                <li>All rights belong to the respective publishers, writers, and reporters</li>
                <li>Our summaries are informational and transformative</li>
                <li>Source links are provided for transparency</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-[#202124] mb-4">4. User Responsibility</h2>
              <p className="text-[#5F6368] mb-4 leading-relaxed">
                If you create an account:
              </p>
              <ul className="list-disc pl-6 text-[#5F6368] mb-4 space-y-2">
                <li>You are responsible for maintaining your login security</li>
                <li>You must not misuse the platform</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-[#202124] mb-4">5. Acceptable Use</h2>
              <p className="text-[#5F6368] mb-4 leading-relaxed">
                You agree not to:
              </p>
              <ul className="list-disc pl-6 text-[#5F6368] mb-4 space-y-2">
                <li>Abuse or disrupt the website</li>
                <li>Attempt unauthorized access</li>
                <li>Use the platform for illegal purposes</li>
                <li>Misrepresent AI-generated content as original reporting</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-[#202124] mb-4">6. AI Disclaimer</h2>
              <p className="text-[#5F6368] mb-4 leading-relaxed">
                You acknowledge that:
              </p>
              <ul className="list-disc pl-6 text-[#5F6368] mb-4 space-y-2">
                <li>Content is generated automatically</li>
                <li>Errors may occur</li>
                <li>Information is provided "as is"</li>
                <li>Lanka News Room is not responsible for decisions made based on summaries</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-[#202124] mb-4">7. Reporting Content</h2>
              <p className="text-[#5F6368] mb-4 leading-relaxed">
                If you find:
              </p>
              <ul className="list-disc pl-6 text-[#5F6368] mb-4 space-y-2">
                <li>Incorrect information</li>
                <li>Offensive or irrelevant content</li>
                <li>Technical issues</li>
              </ul>
              <p className="text-[#5F6368] mb-4 leading-relaxed">
                Please report it immediately:
              </p>
              <p className="text-[#5F6368] mb-4 leading-relaxed">
                <a 
                  href="mailto:nathanbenaiah4@gmail.com"
                  className="text-[#1A73E8] hover:underline"
                >
                  📧 nathanbenaiah4@gmail.com
                </a>
              </p>
              <p className="text-[#5F6368] mb-4 leading-relaxed">
                We actively review reports to improve the system.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-[#202124] mb-4">8. Limitation of Liability</h2>
              <p className="text-[#5F6368] mb-4 leading-relaxed">
                Lanka News Room is not liable for:
              </p>
              <ul className="list-disc pl-6 text-[#5F6368] mb-4 space-y-2">
                <li>Errors in AI-generated summaries</li>
                <li>Losses caused by reliance on content</li>
                <li>Content on external websites linked as sources</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-[#202124] mb-4">9. Termination</h2>
              <p className="text-[#5F6368] mb-4 leading-relaxed">
                Access may be restricted or removed if:
              </p>
              <ul className="list-disc pl-6 text-[#5F6368] mb-4 space-y-2">
                <li>These terms are violated</li>
                <li>The platform is misused</li>
                <li>Required by law</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-[#202124] mb-4">10. Governing Law</h2>
              <p className="text-[#5F6368] mb-4 leading-relaxed">
                These Terms are governed by the laws of Sri Lanka.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-[#202124] mb-4">11. Changes to Terms</h2>
              <p className="text-[#5F6368] mb-4 leading-relaxed">
                Terms may be updated at any time.
              </p>
              <p className="text-[#5F6368] mb-4 leading-relaxed">
                Continued use of the website means acceptance of updated terms.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-[#202124] mb-4">12. Contact</h2>
              <p className="text-[#5F6368] mb-4 leading-relaxed">
                <a 
                  href="mailto:nathanbenaiah4@gmail.com"
                  className="text-[#1A73E8] hover:underline"
                >
                  📧 nathanbenaiah4@gmail.com
                </a>
              </p>
            </section>

            <div className="mt-8 pt-6 border-t border-[#E8EAED]">
              <Link 
                href="/" 
                className="text-[#1A73E8] hover:underline font-medium"
              >
                ← Back to Home
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

