-- Add missing metadata columns to clusters table
-- These columns store metadata generated by the pipeline (SEO, topics, entities, etc.)

-- Add slug column with unique index
ALTER TABLE clusters ADD COLUMN IF NOT EXISTS slug TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS clusters_slug_idx ON clusters(slug) WHERE slug IS NOT NULL;

-- Add published_at for date filtering
ALTER TABLE clusters ADD COLUMN IF NOT EXISTS published_at TIMESTAMPTZ;
CREATE INDEX IF NOT EXISTS clusters_published_at_idx ON clusters(published_at DESC);

-- Add topic for topic filtering
ALTER TABLE clusters ADD COLUMN IF NOT EXISTS topic TEXT;
CREATE INDEX IF NOT EXISTS clusters_topic_idx ON clusters(topic) WHERE topic IS NOT NULL;

-- Add city for location filtering
ALTER TABLE clusters ADD COLUMN IF NOT EXISTS city TEXT;
CREATE INDEX IF NOT EXISTS clusters_city_idx ON clusters(city) WHERE city IS NOT NULL;

-- Add primary_entity for entity search
ALTER TABLE clusters ADD COLUMN IF NOT EXISTS primary_entity TEXT;

-- Add event_type for event type filtering
ALTER TABLE clusters ADD COLUMN IF NOT EXISTS event_type TEXT;
CREATE INDEX IF NOT EXISTS clusters_event_type_idx ON clusters(event_type) WHERE event_type IS NOT NULL;

-- Add image_url
ALTER TABLE clusters ADD COLUMN IF NOT EXISTS image_url TEXT;

-- Add language (using existing lang_code enum)
ALTER TABLE clusters ADD COLUMN IF NOT EXISTS language lang_code DEFAULT 'en'::lang_code;

-- Add SEO metadata columns for all languages
ALTER TABLE clusters ADD COLUMN IF NOT EXISTS meta_title_en TEXT;
ALTER TABLE clusters ADD COLUMN IF NOT EXISTS meta_description_en TEXT;
ALTER TABLE clusters ADD COLUMN IF NOT EXISTS meta_title_si TEXT;
ALTER TABLE clusters ADD COLUMN IF NOT EXISTS meta_description_si TEXT;
ALTER TABLE clusters ADD COLUMN IF NOT EXISTS meta_title_ta TEXT;
ALTER TABLE clusters ADD COLUMN IF NOT EXISTS meta_description_ta TEXT;

-- Add comments for documentation
COMMENT ON COLUMN clusters.slug IS 'SEO-friendly URL slug for the cluster';
COMMENT ON COLUMN clusters.published_at IS 'Original publication date of the news';
COMMENT ON COLUMN clusters.topic IS 'Primary topic (politics, economy, sports, etc.)';
COMMENT ON COLUMN clusters.city IS 'Primary city/location mentioned in the news';
COMMENT ON COLUMN clusters.primary_entity IS 'Main person/organization mentioned';
COMMENT ON COLUMN clusters.event_type IS 'Type of event (election, court, accident, etc.)';
COMMENT ON COLUMN clusters.image_url IS 'Best selected image URL for the cluster';
COMMENT ON COLUMN clusters.language IS 'Primary language of the source articles';

